global_frame: odom
rolling_window: true
width: 5.0
height: 5.0
publish_frequency: 3
update_frequency: 5.0


plugins:
  - {name: obstacles,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,           type: "costmap_2d::InflationLayer"}


#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: robot_base/scan, inf_is_valid: true, max_obstacle_height: 0.8}

inflation:
    inflation_radius: 0.1
    cost_scaling_factor: 0.5

